title: Joseph Resch
email: jresch@ucla.edu
tagline: Statistician & Data Scientist
description: >-
  Statistics Ph.D. from UCLA with a background in economics. Experienced in Bayesian modeling, causal inference, experimentation, and machine learning.
baseurl: ""
url: "https://josephresch.github.io"
github_username: josephresch
linkedin_username: joseph-resch
theme: minima
plugins:
  - jekyll-feed
header_pages: []

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
