title: Joseph Resch
email: jresch@ucla.edu
description: >-
  Statistics Ph.D. candidate at UCLA with experience in machine learning,
  Bayesian modeling, and applied data science.
baseurl: ""
url: "https://josephresch.github.io"
linkedin_username: joseph-resch
github_username: josephresch
theme: researcher
plugins:
  - jekyll-feed
header_pages:
  - about.markdown
  - research.md
  - projects.md
  - contact.md
